-- UserSettings was generated by the starter template and has no application owner.
-- It has never been read or written; remove the dead table without touching IdP data.
DROP TABLE IF EXISTS "UserSettings";
